<!--
 * @Author: 吴楚标
 * @Date: 2021-06-16 20:43:05
 * @LastEditors: 吴楚标
 * @LastEditTime: 2021-06-16 20:50:07
 * @Description: 
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>await 函数</title>
</head>
<body>
  <script>
    async function main(){
      let p = new Promise((resolve, reject) => {
        // resolve('ok');
        reject('error');
      })
      // 1.右侧为promise的情况
      // let res = await p;
      // 2.右侧为其他类型的数据
      // let res2 = await 20;
      // 3.如果promise是失败的状态
      try{
        let res3 = await p;
      }catch(e){
        console.log(e);
      }
      // console.log(res2);
    }
    
    main();
  </script>
</body>
</html>